spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/BankingApp
    username: postgres
    password: naruto
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect : org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
